name: Conventional Commits

on:
  pull_request:
    branches: [ develop, master ]
  push:
    branches: [ develop, master, feature/*, fix/*, chore/*, refactor/*]

jobs:
  build:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webiny/action-conventional-commits@v1.1.0
        # optional, required for private repos
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}